### ISSUE TITLE
Epic: Prepare first two lessons for pilot workshop

### ISSUE THREAD

**Issue by e-belfer** [catalyst-cooperative/open-energy-data-for-all#3]
### Overview

Following the Collaborative Lesson Development Training, we have a very rough skeleton of our lesson plan. This epic will help us keep track of our progress towards presenting our first pilot workshop on the first 2 coding episodes of our lesson (episodes 2+3, currently).

### Success Criteria

We are ready to present 1-2 episodes of our lesson as a pilot workshop to 10-15 students by January 2025, before part 2 of the CLDT training.

### Breakdown of tasks

```[tasklist]
### Target Audience
- [ ] Clean up target audience description
- [x] Finalize pre-requisite list
- [x] Link to equivalent pre-requisites. If any aren't covered by other Carpentries workshops, provide open-source alternatives.
- [ ] https://github.com/catalyst-cooperative/open-energy-data-for-all/pull/4
- [ ] https://github.com/catalyst-cooperative/open-energy-data-for-all/pull/5
- [ ] https://github.com/catalyst-cooperative/open-energy-data-for-all/issues/6
```

```[tasklist] 
### Lesson objectives
* [ ] Clean up first draft of learning objectives
* [ ] Check against the SMART criteria
* [ ] Update on workbench
* [ ] Check against existing list of lessons, update one or the other as needed
```

```[tasklist]
### Dataset and narrative
- [ ] https://github.com/catalyst-cooperative/open-energy-data-for-all/issues/8
- [ ] https://github.com/catalyst-cooperative/open-energy-data-for-all/issues/7
```

```[tasklist]
### Lesson setup
- [ ] https://github.com/catalyst-cooperative/open-energy-data-for-all/issues/19
- [ ] Flesh out any problematic areas in the setup
```

```[tasklist]
### Lesson prep: First Drafts of Chapter I
- [ ] https://github.com/catalyst-cooperative/open-energy-data-for-all/issues/24
- [ ] https://github.com/catalyst-cooperative/open-energy-data-for-all/issues/13
- [ ] https://github.com/catalyst-cooperative/open-energy-data-for-all/issues/14
- [ ] https://github.com/catalyst-cooperative/open-energy-data-for-all/issues/22
```
```[tasklist]
### Integrate feedback on lessons
- [ ] https://github.com/catalyst-cooperative/open-energy-data-for-all/issues/17
- [ ] https://github.com/catalyst-cooperative/open-energy-data-for-all/issues/18
```

```[tasklist] 
### Set up pilot
* [ ] Finalize online vs offline
* [ ] Select date
* [ ] Set up pre-survey and post-survey forms
* [ ] Publicize
```
