### ISSUE TITLE
Clean up learner profiles

### ISSUE THREAD

**Issue by e-belfer** [catalyst-cooperative/open-energy-data-for-all#6]
```[tasklist]
### Tasks
- [x] Sparky probably already knows how to read in CSV files using Pandas.
- [x] Make Sparky a second-year
- [x] Sparky might want to transform data provided in a new format that wasn't covered by the postdoc's work, or explore automation or scraping on the ingestion side
- [x] Gene might be interested in automating and versioning data collection, so that others don't have to manually download all the input data or get it from him. A colleague ran this with data they just downloaded and got totally different results.
- [x] Saul has played around with some data for a single county, but now they want to scale up to the US - interested in large-scale scraping of data collection. And maybe also have run into some other weird formats they don't even know what they are.
- [x] Gene - drop Github from learning objectives. Gene has already used Github for personal projects.
```
